"""Type stubs for kaos_graph._rust.algorithms."""

from typing import Any

from kaos_graph._rust.graph import PyGraph

# Traversal
def bfs(graph: PyGraph, source: str) -> list[str]: ...
def dfs(graph: PyGraph, source: str) -> list[str]: ...
def bfs_with_depth(graph: PyGraph, source: str) -> list[tuple[str, int]]: ...
def bfs_at_depth(graph: PyGraph, source: str, depth: int) -> list[str]: ...
def dfs_events(graph: PyGraph, source: str) -> list[tuple[str, str]]: ...

# Paths
def shortest_paths(
    graph: PyGraph,
    source: str,
    target: str | None = None,
    weight_key: str | None = None,
) -> dict[str, float]: ...
def shortest_path_length(
    graph: PyGraph,
    source: str,
    target: str,
    weight_key: str | None = None,
) -> float | None: ...
def has_path(graph: PyGraph, source: str, target: str) -> bool: ...
def astar_path(
    graph: PyGraph,
    source: str,
    target: str,
    weight_key: str | None = None,
) -> dict[str, Any] | None: ...
def bellman_ford_paths(
    graph: PyGraph,
    source: str,
    weight_key: str | None = None,
) -> dict[str, float]: ...
def all_simple_paths(
    graph: PyGraph,
    source: str,
    target: str,
    max_depth: int = 32,
    max_paths: int = 10_000,
) -> list[list[str]]: ...
def find_cycles(graph: PyGraph) -> list[list[str]]: ...
def find_cycle_paths(graph: PyGraph) -> list[list[str]]: ...

# Components
def strongly_connected_components(graph: PyGraph) -> list[list[str]]: ...
def num_connected_components(graph: PyGraph) -> int: ...
def weakly_connected_components(graph: PyGraph) -> list[list[str]]: ...
def is_strongly_connected(graph: PyGraph) -> bool: ...
def is_weakly_connected(graph: PyGraph) -> bool: ...

# DAG
def topological_sort(graph: PyGraph) -> list[str]: ...
def ancestors(graph: PyGraph, id: str) -> list[str]: ...
def descendants(graph: PyGraph, id: str) -> list[str]: ...
def longest_path(graph: PyGraph) -> dict[str, Any]: ...

# Centrality
def pagerank(
    graph: PyGraph,
    damping_factor: float = 0.85,
    iterations: int = 100,
) -> list[tuple[str, float]]: ...
def degree_centrality(graph: PyGraph) -> list[tuple[str, float]]: ...
def in_degree_centrality(graph: PyGraph) -> list[tuple[str, float]]: ...
def out_degree_centrality(graph: PyGraph) -> list[tuple[str, float]]: ...
def betweenness_centrality(graph: PyGraph, normalized: bool = True) -> list[tuple[str, float]]: ...
def closeness_centrality(graph: PyGraph) -> list[tuple[str, float]]: ...
def eigenvector_centrality(
    graph: PyGraph, iterations: int = 100, tolerance: float = 1e-6
) -> list[tuple[str, float]]: ...

# Community
def louvain_communities(graph: PyGraph) -> list[list[str]]: ...
def label_propagation(graph: PyGraph) -> list[list[str]]: ...

# Structure
def bridges(graph: PyGraph) -> list[tuple[str, str]]: ...
def greedy_matching(graph: PyGraph) -> list[tuple[str, str]]: ...
def maximum_matching(graph: PyGraph) -> list[tuple[str, str]]: ...
def maximal_cliques(
    graph: PyGraph,
    max_input_nodes: int = 1000,
    max_cliques: int = 10_000,
) -> list[list[str]]: ...
def density(graph: PyGraph) -> float: ...
def is_bipartite(graph: PyGraph) -> bool: ...
def transitive_closure(graph: PyGraph) -> PyGraph: ...
def condensation(graph: PyGraph) -> PyGraph: ...
def articulation_points(graph: PyGraph) -> list[str]: ...
def k_clique_communities(graph: PyGraph, k: int) -> list[list[str]]: ...
