"""Type stubs for kaos_graph._rust.graph."""

from typing import Any

class PyGraph:
    def __init__(
        self, directed: bool = True, name: str | None = None, multi: bool = False
    ) -> None: ...
    def add_node(self, id: str, properties: dict[str, Any] | None = None) -> None: ...
    def add_edge(
        self, source: str, target: str, properties: dict[str, Any] | None = None
    ) -> None: ...
    def remove_node(self, id: str) -> dict[str, Any]: ...
    def remove_edge(self, source: str, target: str) -> None: ...
    def update_node(self, id: str, properties: dict[str, Any] | None = None) -> None: ...
    def set_node_property(self, id: str, key: str, value: Any) -> None: ...
    def node(self, id: str) -> dict[str, Any] | None: ...
    def node_ids(self) -> list[str]: ...
    def edges(self) -> list[tuple[str, str, dict[str, Any]]]: ...
    def successors(self, id: str) -> list[str]: ...
    def predecessors(self, id: str) -> list[str]: ...
    def neighbors(self, id: str) -> list[str]: ...
    def degree(self, id: str) -> int: ...
    def has_node(self, id: str) -> bool: ...
    def has_edge(self, source: str, target: str) -> bool: ...
    @property
    def n_nodes(self) -> int: ...
    @property
    def n_edges(self) -> int: ...
    @property
    def is_directed(self) -> bool: ...
    @property
    def name(self) -> str: ...
    def is_dag(self) -> bool: ...
    def nodes_filtered(self, key: str, value: Any) -> list[str]: ...
    def edges_filtered(self, key: str, value: Any) -> list[tuple[str, str, dict[str, Any]]]: ...
    def subgraph(self, node_ids: list[str]) -> PyGraph: ...
    def ego_graph(self, center: str, radius: int) -> PyGraph: ...
    def is_connected(self) -> bool: ...
    def is_tree(self) -> bool: ...
    def reverse(self) -> PyGraph: ...
    def to_undirected(self) -> PyGraph: ...
    @property
    def is_multi(self) -> bool: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(
        data: str,
        max_bytes: int,
        max_nodes: int,
        max_edges: int,
    ) -> PyGraph: ...
    def __len__(self) -> int: ...
    def __contains__(self, id: str) -> bool: ...
    def __repr__(self) -> str: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
