"""Type stubs for kaos_graph._rust.knowledge."""

from typing import Any

from kaos_graph._rust.graph import PyGraph

def merge_graphs(base: PyGraph, other: PyGraph, conflict: str = "keep_latest") -> PyGraph: ...
def diff_graphs(old: PyGraph, new: PyGraph) -> dict[str, Any]: ...
def extract_subgraph_by_property(graph: PyGraph, key: str, value: Any) -> PyGraph: ...
def extract_subgraph_by_types(graph: PyGraph, types: list[str]) -> PyGraph: ...
def project_triples(graph: PyGraph) -> list[tuple[str, str, str]]: ...
def from_triples(triples: list[tuple[str, str, str]], directed: bool = True) -> PyGraph: ...
def infer_types(graph: PyGraph, predicate_iri: str) -> PyGraph: ...
def densify(graph: PyGraph, predicate: str) -> PyGraph: ...
def find_orphan_nodes(graph: PyGraph) -> list[str]: ...
def find_hub_nodes(graph: PyGraph, threshold: int) -> list[str]: ...
def degree_distribution(graph: PyGraph) -> dict[int, int]: ...
